---
- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"
  tags:
    - checks

- name: "Ensure that ssl target directories exists"
  file: path=/etc/letsencrypt/{{ item }}/{{ aws_target_domain }} state=directory mode=0755 owner=root
  with_items:
    - archive
    - live
  tags:
    - checks

- name: "Transfer ssl cert files file to loadbalancers"
  synchronize:
    mode: push
    src: "/tmp/{{ aws_target_domain }}/ssl-certs/{{ item }}/{{ aws_target_domain }}/"
    dest: "/etc/letsencrypt/{{ item }}/{{ aws_target_domain }}/"
    links: yes
    recursive: yes
    delete: yes
  with_items:
    - archive
    - live
  delegate_to: localhost

- name: validate nginx configuration
  command: nginx -t
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
