- name: Generate letsencrypt certificates
  hosts: docker-host
  become: yes
  roles:
    - generate-nginx-confs
    - { role: generate-ssl-certs, when: generate_ssl_cert }

- name: Deploy configurations on loadbalancers
  hosts: loadbalancers
  become: yes
  roles:
    - { role: deploy-nginx-conf, when: deploy_nginx_conf }
    - { role: deploy-certs, when: deploy_ssl_cert }
