---
- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"
  tags:
    - checks

- name: "Ensure that nginx target directories exists"
  file: path=/etc/nginx/conf.d/domains/http/{{ aws_target_domain }} state=directory mode=0644
  tags:
    - checks

- name: "Ensure that ssl target directories exists"
  file: path=/etc/letsencrypt/{{ item }}/{{ aws_target_domain }} state=directory mode=0644
  with_items:
    - archive
    - live
  tags:
    - checks

- name: "Transfer nginx conf files file to loadbalancers"
  synchronize:
    src: "{{ certsgen_output_dir }}/{{ aws_target_domain }}/nginx-confs/{{ item }}/{{ aws_target_domain }}"
    dest: "/etc/nginx/{{ item }}/{{ aws_target_domain }}"
  with_items:
    - conf.d/domains/http
    - conf.d/domains/https
  delegate_to: "{{ source_hostname }}"

- name: "Transfer ssl cert files file to loadbalancers"
  synchronize:
    src: "{{ certsgen_output_dir }}/{{ aws_target_domain }}/ssl-certs/{{ item }}/{{ aws_target_domain }}/"
    dest: "/etc/letsencrypt/{{ item }}/{{ aws_target_domain }}/"
  with_items:
    - archive
    - live
  delegate_to: "{{ source_hostname }}"

- name: validate nginx configuration
  command: nginx -t
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
